name: Format check

on: [push, pull_request]

jobs:
  check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Clone repository
        uses: actions/checkout@v3
      - name: 🔩 Install Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: 🚀 Check formatting
        run: deno task fmt:check