name: Prettier check

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 check:
  name: Format check
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v3
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: 7
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: 16
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Check formatting
     run: "pnpm run format:check"
