name: Update readme

on:
 schedule:
  - cron: "*/15 * * * *"
 workflow_dispatch:

jobs:
 main:
  name: ✨ README Stats
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v7
     with:
      fetch-depth: 1
   - name: 🔩 Setup Bun
     uses: oven-sh/setup-bun@v2
   - name: 📦 Install dependencies
     run: bun install
   - name: ✨ Generate README.md
     run: bun start
     env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      BYPASS_TOKEN: ${{ secrets.BYPASS_TOKEN }}
   - name: 🚀 Save changes
     run: |
      if [[ "$(git status --porcelain)" != "" ]]; then
      git config user.name IgorKowalczykBot
      git config user.email igor.kowalczyk.bot@onet.pl
      git add .
      git commit -m "[Bot] Update blog feed and activity"
      git push -f
      fi
